/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_AHB2ENR  *((uint32_t*)0x4002104C)
#define RCC_AHB2ENR_GPIOAEN 1<< 0


typedef struct{
	uint32_t MODER;
	uint32_t OTYPER;
	uint32_t OSPEEDR;
	uint32_t PUPDR;
	uint32_t IDR;
	uint32_t ODR;
	uint32_t BSRR;
	uint32_t LCKR;
	uint32_t AFRL;
	uint32_t AFRH;
	uint32_t BRR;
	uint32_t ASCR;
}GPIO_T;

#define GPIOA  ((GPIO_T*)0x48000000)


int main(void)
{
	RCC_AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	GPIOA->MODER&= ~(3<<10);
	GPIOA->MODER|=(1<<10);



	//MODER
	//GPIOA_MODER &= ~(3<<10);
	//GPIOA_MODER |= (1<<10);
    /* Loop forever */
	for(;;){

		GPIOA->ODR |= (1<<5);
		delay(1000);
		GPIOA->ODR &= ~(1<<5);
		delay(1000);
	}
}
void delay(int n) {
    int i;
    for (; n > 0; n--)
        for (i = 0; i < 500; i++) ;
}
