/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Memory map for all busses */
#define PERIPH_BASE                     (0x40000000U)
//#define FMC1_BANK_BASE                  (0x60000000U)
//#define FMC3_BANK_BASE                  (0x80000000U)
//#define QUADSPI_BANK_BASE               (0x90000000U)
//#define FMC_QUADSPI_BASE                (0xA0000000U)
//#define INFO_BASE                       (0x1fff0000U)
#define PERIPH_BASE_APB1                (PERIPH_BASE + 0x00000)
#define PERIPH_BASE_APB2                (PERIPH_BASE + 0x10000)
#define PERIPH_BASE_AHB1                (PERIPH_BASE + 0x20000)
#define PERIPH_BASE_AHB2                (0x48000000U)

/* AHB2 */
#define GPIO_PORT_A_BASE                (PERIPH_BASE_AHB2 + 0x0000)
#define GPIO_PORT_B_BASE                (PERIPH_BASE_AHB2 + 0x0400)
#define GPIO_PORT_C_BASE                (PERIPH_BASE_AHB2 + 0x0800)
#define GPIO_PORT_D_BASE                (PERIPH_BASE_AHB2 + 0x0c00)
#define GPIO_PORT_E_BASE                (PERIPH_BASE_AHB2 + 0x1000)
#define GPIO_PORT_F_BASE                (PERIPH_BASE_AHB2 + 0x1400)
#define GPIO_PORT_G_BASE                (PERIPH_BASE_AHB2 + 0x1800)
#define GPIO_PORT_H_BASE                (PERIPH_BASE_AHB2 + 0x1c00)

#define GPIOA                           GPIO_PORT_A_BASE
#define GPIOB                           GPIO_PORT_B_BASE
#define GPIOC                           GPIO_PORT_C_BASE
#define GPIOD                           GPIO_PORT_D_BASE
#define GPIOE                           GPIO_PORT_E_BASE
#define GPIOF                           GPIO_PORT_F_BASE

#define MMIO32(addr) (*(volatile unsigned int*)(addr))

#define RCC_AHB1ENR_OFFSET 0x48
#define RCC_AHB2ENR_OFFSET 0x4C
#define RCC_BASE  (PERIPH_BASE_AHB1 + 0x1000)
#define RCC_AHB1ENR  MMIO32(RCC_BASE + RCC_AHB1ENR_OFFSET)
#define RCC_AHB2ENR  MMIO32(RCC_BASE + RCC_AHB2ENR_OFFSET)

/* --- GPIO registers for STM32F2, STM32F3 and STM32F4 --------------------- */

/* Port mode register (GPIOx_MODER) */
#define GPIO_MODER(port)                MMIO32((port) + 0x00)
#define GPIOA_MODER                     GPIO_MODER(GPIOA)
#define GPIOB_MODER                     GPIO_MODER(GPIOB)
#define GPIOC_MODER                     GPIO_MODER(GPIOC)
#define GPIOD_MODER                     GPIO_MODER(GPIOD)
#define GPIOE_MODER                     GPIO_MODER(GPIOE)
#define GPIOF_MODER                     GPIO_MODER(GPIOF)

/* Port output type register (GPIOx_OTYPER) */
#define GPIO_OTYPER(port)               MMIO32((port) + 0x04)
#define GPIOA_OTYPER                    GPIO_OTYPER(GPIOA)
#define GPIOB_OTYPER                    GPIO_OTYPER(GPIOB)
#define GPIOC_OTYPER                    GPIO_OTYPER(GPIOC)
#define GPIOD_OTYPER                    GPIO_OTYPER(GPIOD)
#define GPIOE_OTYPER                    GPIO_OTYPER(GPIOE)
#define GPIOF_OTYPER                    GPIO_OTYPER(GPIOF)

/* Port output speed register (GPIOx_OSPEEDR) */
#define GPIO_OSPEEDR(port)              MMIO32((port) + 0x08)
#define GPIOA_OSPEEDR                   GPIO_OSPEEDR(GPIOA)
#define GPIOB_OSPEEDR                   GPIO_OSPEEDR(GPIOB)
#define GPIOC_OSPEEDR                   GPIO_OSPEEDR(GPIOC)
#define GPIOD_OSPEEDR                   GPIO_OSPEEDR(GPIOD)
#define GPIOE_OSPEEDR                   GPIO_OSPEEDR(GPIOE)
#define GPIOF_OSPEEDR                   GPIO_OSPEEDR(GPIOF)

/* Port pull-up/pull-down register (GPIOx_PUPDR) */
#define GPIO_PUPDR(port)                MMIO32((port) + 0x0c)
#define GPIOA_PUPDR                     GPIO_PUPDR(GPIOA)
#define GPIOB_PUPDR                     GPIO_PUPDR(GPIOB)
#define GPIOC_PUPDR                     GPIO_PUPDR(GPIOC)
#define GPIOD_PUPDR                     GPIO_PUPDR(GPIOD)
#define GPIOE_PUPDR                     GPIO_PUPDR(GPIOE)
#define GPIOF_PUPDR                     GPIO_PUPDR(GPIOF)

/* Port input data register (GPIOx_IDR) */
#define GPIO_IDR(port)                  MMIO32((port) + 0x10)
#define GPIOA_IDR                       GPIO_IDR(GPIOA)
#define GPIOB_IDR                       GPIO_IDR(GPIOB)
#define GPIOC_IDR                       GPIO_IDR(GPIOC)
#define GPIOD_IDR                       GPIO_IDR(GPIOD)
#define GPIOE_IDR                       GPIO_IDR(GPIOE)
#define GPIOF_IDR                       GPIO_IDR(GPIOF)

/* Port output data register (GPIOx_ODR) */
#define GPIO_ODR(port)                  MMIO32((port) + 0x14)
#define GPIOA_ODR                       GPIO_ODR(GPIOA)
#define GPIOB_ODR                       GPIO_ODR(GPIOB)
#define GPIOC_ODR                       GPIO_ODR(GPIOC)
#define GPIOD_ODR                       GPIO_ODR(GPIOD)
#define GPIOE_ODR                       GPIO_ODR(GPIOE)
#define GPIOF_ODR                       GPIO_ODR(GPIOF)

/* Port bit set/reset register (GPIOx_BSRR) */
#define GPIO_BSRR(port)                 MMIO32((port) + 0x18)
#define GPIOA_BSRR                      GPIO_BSRR(GPIOA)
#define GPIOB_BSRR                      GPIO_BSRR(GPIOB)
#define GPIOC_BSRR                      GPIO_BSRR(GPIOC)
#define GPIOD_BSRR                      GPIO_BSRR(GPIOD)
#define GPIOE_BSRR                      GPIO_BSRR(GPIOE)
#define GPIOF_BSRR                      GPIO_BSRR(GPIOF)

/* Port configuration lock register (GPIOx_LCKR) */
#define GPIO_LCKR(port)                 MMIO32((port) + 0x1c)
#define GPIOA_LCKR                      GPIO_LCKR(GPIOA)
#define GPIOB_LCKR                      GPIO_LCKR(GPIOB)
#define GPIOC_LCKR                      GPIO_LCKR(GPIOC)
#define GPIOD_LCKR                      GPIO_LCKR(GPIOD)
#define GPIOE_LCKR                      GPIO_LCKR(GPIOE)
#define GPIOF_LCKR                      GPIO_LCKR(GPIOF)

/* Alternate function low register (GPIOx_AFRL) */
#define GPIO_AFRL(port)                 MMIO32((port) + 0x20)
#define GPIOA_AFRL                      GPIO_AFRL(GPIOA)
#define GPIOB_AFRL                      GPIO_AFRL(GPIOB)
#define GPIOC_AFRL                      GPIO_AFRL(GPIOC)
#define GPIOD_AFRL                      GPIO_AFRL(GPIOD)
#define GPIOE_AFRL                      GPIO_AFRL(GPIOE)
#define GPIOF_AFRL                      GPIO_AFRL(GPIOF)

 /* Alternate function high register (GPIOx_AFRH) */
#define GPIO_AFRH(port)                 MMIO32((port) + 0x24)
#define GPIOA_AFRH                      GPIO_AFRH(GPIOA)
#define GPIOB_AFRH                      GPIO_AFRH(GPIOB)
#define GPIOC_AFRH                      GPIO_AFRH(GPIOC)
#define GPIOD_AFRH                      GPIO_AFRH(GPIOD)
#define GPIOE_AFRH                      GPIO_AFRH(GPIOE)
#define GPIOF_AFRH                      GPIO_AFRH(GPIOF)

void delayMs(int n);

int main(void) {

	  RCC_AHB2ENR |=  1;              /* enable GPIOA clock */

    GPIOA_MODER &= ~0x00000C00;     /* clear pin mode */
    GPIOA_MODER |=  0x00000400;     /* set pin to output mode */

    while(1) {
       GPIOA_BSRR = 0x00000020;    /* turn on LED */
        delay();
       GPIOA_BSRR = 0x00200000;    /* turn off LED */
        delay();
    }
}

/* 16 MHz SYSCLK
void delayMs(int n) {
    int i;
    for (; n > 0; n--)
        for (i = 0; i < 3195; i++) ;
} */
void delay(void)
{
	for(uint32_t i = 0; i < 500000; i ++);
}
